# Generated by Django 5.2.17 on 2026-08-28 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj_cpf', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números, com 10 ou 11 dígitos (DDD + número).', regex='^\\d{10,11}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('analise', 'Em Análise'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('data_inicio', models.DateField()),
                ('prazo_vencimento', models.DateField()),
                ('responsavel', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('data_limite', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('cumprido', 'Cumprido'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimentos', to='clientes.projeto')),
            ],
        ),
    ]
